# Generated by Django 4.0.3 on 2022-03-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='student name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_class.studentclass', verbose_name='student class')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
